[2025-03-09T19:02:28.233+0000] {processor.py:156} INFO - Started process (PID=29) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:02:28.234+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:02:28.235+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:02:28.234+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:02:28.236+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:02:28.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:02:28.237+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:02:28.251+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.020 seconds
[2025-03-09T19:02:58.365+0000] {processor.py:156} INFO - Started process (PID=31) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:02:58.372+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:02:58.372+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:02:58.372+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:02:58.374+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:02:58.374+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:02:58.374+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:02:58.389+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.026 seconds
[2025-03-09T19:03:04.424+0000] {processor.py:156} INFO - Started process (PID=33) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:03:04.432+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:03:04.432+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:03:04.432+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:03:04.434+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:03:04.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:03:04.435+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:03:04.449+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.027 seconds
[2025-03-09T19:03:34.549+0000] {processor.py:156} INFO - Started process (PID=35) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:03:34.555+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:03:34.556+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:03:34.556+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:03:34.559+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:03:34.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:03:34.559+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:03:34.572+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.026 seconds
[2025-03-09T19:04:04.675+0000] {processor.py:156} INFO - Started process (PID=37) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:04:04.682+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:04:04.683+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:04:04.683+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:04:04.685+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:04:04.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:04:04.685+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:04:04.698+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.025 seconds
[2025-03-09T19:04:34.801+0000] {processor.py:156} INFO - Started process (PID=39) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:04:34.802+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:04:34.802+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:04:34.802+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:04:34.804+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:04:34.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:04:34.804+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:04:34.818+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.019 seconds
[2025-03-09T19:05:04.921+0000] {processor.py:156} INFO - Started process (PID=41) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:05:04.928+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:05:04.928+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:05:04.928+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:05:04.930+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:05:04.930+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:05:04.930+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:05:04.945+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.026 seconds
[2025-03-09T19:05:35.045+0000] {processor.py:156} INFO - Started process (PID=43) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:05:35.051+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:05:35.052+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:05:35.052+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:05:35.054+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:05:35.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:05:35.054+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:05:35.067+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.025 seconds
[2025-03-09T19:06:05.165+0000] {processor.py:156} INFO - Started process (PID=45) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:06:05.165+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:06:05.166+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:06:05.166+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:06:05.167+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:06:05.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:06:05.168+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:06:05.181+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.019 seconds
[2025-03-09T19:06:35.288+0000] {processor.py:156} INFO - Started process (PID=47) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:06:35.295+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:06:35.296+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:06:35.296+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:06:35.298+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:06:35.297+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:06:35.298+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:06:35.312+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.026 seconds
[2025-03-09T19:07:05.413+0000] {processor.py:156} INFO - Started process (PID=49) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:07:05.420+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:07:05.421+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:07:05.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:07:05.423+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:07:05.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:07:05.423+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:07:05.437+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.026 seconds
[2025-03-09T19:07:35.541+0000] {processor.py:156} INFO - Started process (PID=51) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:07:35.548+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:07:35.548+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:07:35.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:07:35.551+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:07:35.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:07:35.551+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:07:35.564+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.025 seconds
[2025-03-09T19:08:05.661+0000] {processor.py:156} INFO - Started process (PID=53) to work on /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:08:05.668+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/simblock_workflow.py for tasks to queue
[2025-03-09T19:08:05.668+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:08:05.668+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:08:05.670+0000] {logging_mixin.py:149} INFO - [2025-03-09T19:08:05.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/simblock_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simblock_workflow.py", line 114
    start_task >> end_task
    ^
IndentationError: unexpected indent
[2025-03-09T19:08:05.670+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/simblock_workflow.py
[2025-03-09T19:08:05.683+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/simblock_workflow.py took 0.025 seconds
